### ISSUE TITLE
Can't load libaps and libaps2 libraries at the same time in Matlab

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/libaps#4]
```
>> aps2 = APS2()
aps2 = 
  APS2 with properties:

         ip_addr: ''
         libpath: '../../build'
    samplingRate: 1.200000000000000e+09
>> aps1 = APS()
Error using loadlibrary
There was an error loading the library
"C:\...\...\...\MATLAB\libaps\release\build\libaps.dll"
The specified procedure could not be found.


Error in APS/load_library (line 527)
                loadlibrary(fullfile(obj.library_path, libfname), protoFile);
Error in APS (line 84)
            obj.load_library();
Caused by:
    Error using loaddefinedlibrary
    The specified procedure could not be found.

>> clear aps2
>> unloadlibrary('libaps2')
>> aps1 = APS()
aps1 = 
  APS with properties:

          library_path: 'C:\...\...\...\MATLAB\libaps\release\src\matlab\@A…'
          library_name: 'libaps'
              deviceID: []
          deviceSerial: []
         bit_file_path: 
....
....


>> aps2 = APS2()
Error using loadlibrary
There was an error loading the library "libaps2"
The specified procedure could not be found.


Error in APS2.load_library (line 269)
                loadlibrary('libaps2', fullfile(curPath, 'libaps2.matlab.h'));
Error in APS2 (line 32)
            APS2.load_library();
Caused by:
    Error using loaddefinedlibrary
    The specified procedure could not be found.

     
>> clear aps1
>> unloadlibrary('libaps')
>> aps2 = APS2()
aps2 = 
  APS2 with properties:

         ip_addr: ''
         libpath: '../../build'
    samplingRate: 1.200000000000000e+09
>> 
```
I'm using the release 1.3.2 version of libaps and the master branch of libaps2.  I've also tried the latest release of libaps2, v1.3.0 and have the same issue.

**Comment by matthewware** [comment]
My initial thoughts are incompatible deps or a shared name somewhere...

**Comment by matthewware** [comment]
@dieris has apparently reproduced the issue as well.

**Comment by matthewware** [comment]
I'm managed to stumble into some progress on this issue.  It seems like Matlab is able to load the compiled libaps2 from the current master and one of the release versions of libaps.   The problem comes to a head when the python executable get mixed with the matlab ones.  Trying to load the compiled version of libaps2 in python leads to an error:

> Entry Point Not Found.  Could not be located in the dynamic link library 

Similarly, if you try to load the 'python' version of the libaps2 into Matlab you get the behavior described above.  So there must be some difference in the conda installed binaries and the locally compiled ones.  This is probably no surprise to others and I'm just out of the loop.  @grahamrow @gribeill @dieris any thoughts?  It seems we have a work around at least for now if you stick to release versions and cmake/locally compiled versions of the libraries.

**Comment by dieris** [comment]
mm...you already went further than I was able to. I couldn't get the libaps library to load even when locally compiled. I may need your help later :)

**Comment by matthewware** [comment]
Another quick update: I can load the release version of libaps and the conda version of libaps2 in python at the same time.  All the other permutations I've tried don't seem to work.  I'll see what it's going to take to get a static binary compiled.

**Comment by matthewware** [comment]
🤦🤦🤦
>qlab@ORION MINGW64 ~/Anaconda3/envs/py4auspex/Library/bin$ ldd libaps2.dll
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fffefc90000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fffefa70000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fffec4d0000)
        WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7fffed370000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7fffefc30000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fffef660000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fffed0f0000)
        IPHLPAPI.DLL => /c/WINDOWS/SYSTEM32/IPHLPAPI.DLL (0x7fffeb750000)
        **zlib.dll => /c/Users/qlab/Anaconda3/envs/py4auspex/Library/bin/zlib.dll (0x7fffe6690000)**
        **MSVCP140.dll => /c/Users/qlab/Anaconda3/envs/py4auspex/Library/bin/MSVCP140.dll (0x7fffd9f70000)**
        **VCRUNTIME140.dll => /c/Users/qlab/Anaconda3/envs/py4auspex/Library/bin/VCRUNTIME140.dll (0x7fffde110000)**
        ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7fffed9b0000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fffed250000)
        CRYPTBASE.DLL => /c/WINDOWS/SYSTEM32/CRYPTBASE.DLL (0x7fffebbd0000)
        bcryptPrimitives.dll => /c/WINDOWS/System32/bcryptPrimitives.dll (0x7fffec1b0000)

>qlab@ORION MINGW64 ~/Documents/GitHub/libaps2/build (master)$ ldd libaps2.dll
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fffefc90000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fffefa70000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fffec4d0000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fffed250000)
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7fffef510000)
        IPHLPAPI.DLL => /c/WINDOWS/SYSTEM32/IPHLPAPI.DLL (0x7fffeb750000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7fffec220000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7fffeda60000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7fffec340000)
       **libhdf5_cpp-0.dll => /c/Users/qlab/Documents/dlls/libhdf5_cpp-0.dll (0x64700000)**
        **libhdf5-0.dll => /c/Users/qlab/Documents/dlls/libhdf5-0.dll (0x68300000)**
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7fffec950000)
        libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x64940000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fffed0f0000)
        WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7fffed370000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7fffefc30000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fffef660000)
        **zlib1.dll => /mingw64/bin/zlib1.dll (0x62e80000)**
        **libszip-0.dll => /c/Users/qlab/Documents/dlls/libszip-0.dll (0x6da40000)**
        ??? => ??? (0x160000)
        **libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x140000)**
        **libstdc++-6.dll => /mingw64/bin/libstdc++-6.dll (0x6fc40000)**
        ??? => ??? (0x610000)
        **libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x140000)**
        **libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x140000)**

-------------------------------------------------------------------------------------------------------------

>qlab@ORION MINGW64 /c/Users/qlab/Documents/GitHub/libaps/build-hdf5$ ldd libaps.dll
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fffefc90000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fffefa70000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fffec4d0000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fffed250000)
        **libhdf5_cpp-0.dll => /mingw64/bin/libhdf5_cpp-0.dll (0x64700000)**
        **libhdf5-0.dll => /mingw64/bin/libhdf5-0.dll (0x68300000)**
        **libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x64940000)**
        FTD2XX.dll => /c/WINDOWS/SYSTEM32/FTD2XX.dll (0x180000000)
        **libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x61440000)**
        **libstdc++-6.dll => /mingw64/bin/libstdc++-6.dll (0x6fc40000)**
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7fffef510000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7fffec220000)
        SETUPAPI.dll => /c/WINDOWS/System32/SETUPAPI.dll (0x7fffedc90000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7fffeda60000)
        cfgmgr32.dll => /c/WINDOWS/System32/cfgmgr32.dll (0x7fffec2f0000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7fffec340000)
        **libszip.dll => /mingw64/bin/libszip.dll (0x62540000)**
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fffed0f0000)
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7fffec950000)
        **zlib1.dll => /mingw64/bin/zlib1.dll (0x62e80000)**
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fffef660000)
        ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7fffed9b0000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7fffefc30000)
        IMM32.DLL => /c/WINDOWS/System32/IMM32.DLL (0x7fffef8c0000)

>qlab@ORION MINGW64 /c/Users/qlab/Documents/dlls/libaps-v1.3.2-windows-x64/release/build$ ldd libaps.dll
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fffefc90000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fffefa70000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fffec4d0000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fffed250000)
        **libgcc_s_seh-1.dll => /c/Users/qlab/Documents/dlls/libaps-v1.3.2-windows-x64/release/build/libgcc_s_seh-1.dll (0x61440000)**
        **libhdf5-0.dll => /c/Users/qlab/Documents/dlls/libaps-v1.3.2-windows-x64/release/build/libhdf5-0.dll (0x68300000)**
        **libstdc++-6.dll => /c/Users/qlab/Documents/dlls/libaps-v1.3.2-windows-x64/release/build/libstdc++-6.dll (0x6fc40000)**
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7fffef510000)
        **libhdf5_cpp-0.dll => /c/Users/qlab/Documents/dlls/libaps-v1.3.2-windows-x64/release/build/libhdf5_cpp-0.dll (0x64700000)**
        **libwinpthread-1.dll => /c/Users/qlab/Documents/dlls/libaps-v1.3.2-windows-x64/release/build/libwinpthread-1.dll (0x64940000)**
        FTD2XX.dll => /c/WINDOWS/SYSTEM32/FTD2XX.dll (0x180000000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7fffec220000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7fffeda60000)
        **zlib1.dll => /c/Users/qlab/Documents/dlls/libaps-v1.3.2-windows-x64/release/build/zlib1.dll (0x62e80000)**
        **libszip-0.dll => /c/Users/qlab/Documents/dlls/libaps-v1.3.2-windows-x64/release/build/libszip-0.dll (0x6da40000)**
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7fffec340000)
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7fffec950000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fffed0f0000)
        SETUPAPI.dll => /c/WINDOWS/System32/SETUPAPI.dll (0x7fffedc90000)
        cfgmgr32.dll => /c/WINDOWS/System32/cfgmgr32.dll (0x7fffec2f0000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fffef660000)
        ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7fffed9b0000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7fffefc30000)
        IMM32.DLL => /c/WINDOWS/System32/IMM32.DLL (0x7fffef8c0000)

**Comment by gribeill** [comment]
From dependency walker:

Error: At least one required implicit or forwarded dependency was not found.
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: Modules with different CPU types were found.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

Uh oh..

**Comment by matthewware** [comment]
This also seems to only be an issue on Windows.  Master branch seems to load in python without issues on Linux and OSX.

**Comment by caryan** [comment]
A comment from the peanut gallery: the `libaps2` Windows conda package is built with MSVC and linked against libhdf5 built with MSVC whereas `libaps` is just built locally with msys2 so I'm not terribly surprised they conflict. I guess I would have thought a fresh build of both with msys2 and putting the dll's and dependent dlls from msys2 on the PATH would work.

**Comment by matthewware** [comment]
Hmm _all_ the dlls not being on the path might explain why python isn't able to load things on _some_ computers.  The environment configurations tend to metastasize over time.  @gribeill do you know which libhdf5 you were using in MSVC earlier?

**Comment by gribeill** [comment]
Thanks @caryan for the hint... I think we're almost there. Need to fix the local build process for the FTDI drivers still for libaps...

**Comment by gribeill** [comment]
Okay, everything is working now and both python and MATLAB can happily talk to both types of APS at once. We'll have to figure out how to properly package everything for release but for now I think this can be closed.
